### ISSUE TITLE
LIBCPP_ASSERT_NON_NULL when running in simulator

### ISSUE THREAD

**Issue by dillondotzip** [mainframecomputer/fullmoon-ios#4]
When trying to run in simulator

I get a `Thread 1: signal SIGABRT` at `_LIBCPP_ASSERT_NON_NULL(__s != nullptr, "basic_string(const char*) detected nullptr");`

**Comment by sahandnayebaziz** [comment]
I think it has to be run either on a physical device or on the `My Mac (Designed for iPad)` destination because [mlx-swift](https://github.com/ml-explore/mlx-swift) requires a direct connection to Metal. I read about that in the [Running on iOS](https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx/running-on-ios) section of their docs.

**Comment by jordansinger** [comment]
+1 to @sahandnayebaziz
